apiVersion: apps/v1
kind: Deployment
metadata:
  name: hadoop-name-node
  labels:
    app: hadoop
spec:
  selector:
    matchLabels:
      app: hadoop
  replicas: 1
  template:
    metadata:
      labels:
        app: hadoop
    spec:
      containers:
        - image: docker.io/bde2020/hadoop-namenode
          name: hadoop-name-node
          ports:
              - containerPort: 8020
          env:
          - name: CLUSTER_NAME
            value: "test"

